apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
    ${NAMESPACE_LABELS}

  spec: 
${PORT_EXPOSE}
    selector:
      svc: ${NAME}
      ${SELECTOR}
      
      
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: ${NAME}
    ${NAMESPACE_LABELS}
  spec:
    replicas: ${REPLICAS}
    template:
      metadata:
        labels:
          svc: ${NAME}
          ${LABELS}
      spec:
      <% if(NODE_TYPE != null){ %>
        ${NODE_SELECTOR}
      <% } %>
        containers:
          - name: ${NAME}
            image: ${IMAGE}
            ports: 
            <% for(data in CONTAINER_PORTS){ %>
              - containerPort: ${data.key}
                protocol: ${data.value}            
            <% } %>
            env:
            <% for(label in ENVS){ %>
            - name: ${label.key}
              value: ${label.value}
            <% } %>
            <% if(VOLUME_TYPE != null){ %>
            ${VOLUME_MOUNT}
            <% } %>
            <% if (RESOURCE_TYPE != null) { %>
            ${RESOURCE}
            <% } %>
            args:
              - catalina.sh
              - run
            imagePullPolicy: IfNotPresent
            
       <% if(VOLUME_TYPE != null){ %>
        ${VOLUME}
        <% } %>

{"parameters":
  [ 
    {
      "description": "服务名称",
      "displayName": "名称",
      "name": "NAME",
      "value": "",
      "select": "",
      "type": "String",
      "required": "true"
    },
    {
      "description": "服务端口",
      "displayName": "端口",
      "name": "PORTS",
      "value": "",
      "select": "",
      "type": "Ports",
      "required": "true"
    },
      <% if(VOLUME_TYPE != null){ %>
    {
      "description": "存储卷",
      "displayName": "选择存储卷",
      "name": "VOLUMES",
      "value": "",
      "select": "",
      "type": "Volumes",
      "required": "true"
    },
    <% } %>
    <% if(RESOURCE_TYPE != null){ %>
    {
      "description": "资源配置",
      "displayName": "修改资源会重新启动所有该组件下的实例",
      "name": "RESOURCE",
      "value": "",
      "select": "",
      "type": "Resource",
      "required": "true"
    },
    <% } %>
    <% if(NODE_TYPE != null){ %>
    {
      "description": "节点调度",
      "displayName": "选择节点需要调度的方式",
      "name": "NODE_SELECTOR",
      "value": "",
      "select": "",
      "type": "NodeSelector",
      "required": "true"
    },
    <% } %>
  ]
}