apiVersion: extensions/v1beta1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    <% } %>
  spec:
    <% if(NODE_TYPE != null){ %>
    type: NodePort
    <% } %>
    ports:
    <% if(ports != null){ %> 
      <% for(port in ports){ %>
      - port: ${port.port}
        nodePort: ${port.nodePort}
        targetPort: ${port.targetPort}
        protocol: ${port.protocol}
        name: http-${port.targetPort}
      <% } %>
      <% } %>
      <% if(nodePorts != null){ %>   
      <% for(port in nodePorts){ %>
      - port: ${port.port}
        targetPort: ${port.targetPort}
        protocol: ${port.protocol}
        name: http-${port.targetPort}
      <% } %>
      <% } %>
    <% for(var i = 0; i < containerPorts.~size; i++){ %>
      - port: ${containerPorts[i].key}
        targetPort: ${containerPorts[i].key}
        protocol: ${containerPorts[i].value}
        name: http-${i}
     <% } %>
    selector:
      app: ${NAME}
    
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: ${NAME}-single-pv
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    <% } %>
    labels:
      release: stable
  spec:
    capacity:
      storage: ${storage}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /tmp/data
      
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}-pv-claim
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    <% } %>
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${storage}
        
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ${NAME}
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    <% } %>
  spec:
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - image: 139.219.239.226/library/mysql_offical:5.6
          name: ${NAME}
          resources:
            limits:
              <% if (LIMITS_CPU != null) { %>
              cpu: ${LIMITS_CPU}
              <% } %>
              <% if (LIMITS_MEMORY != null) { %>
              memory: ${LIMITS_MEMORY}
              <% } %>
            requests:
              <% if (REQUESTS_CPU != null) { %>
              cpu: ${REQUESTS_CPU}
              <% } %>
              <% if (REQUESTS_MEMORY != null) { %>
              memory: ${REQUESTS_MEMORY}
              <% } %>
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          ports:
          - containerPort: 3306
            protocol: TCP
          volumeMounts:
          - name: ${NAME}-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: ${NAME}-persistent-storage
          persistentVolumeClaim:
            claimName: ${NAME}-pv-claim

{"parameters":
  [
    {
      "description": "组件名称",
      "displayName": "名称",
      "name": "NAME",
      "value": "",
      "select": "",
      "type": "String",
      "required": "true"
    },
    {
      "description": "资源配置",
      "displayName": "修改资源会重新启动所有该组件下的实例",
      "name": "RESOURCE",
      "value": "",
      "select": "",
      "type": "Resource",
      "required": "false"
    },
    {
      "description": "mysql外部挂载存储卷大小",
      "displayName": "挂载存储大小",
      "name": "storage",
      "value": "",
      "select": "1",
      "type": "Number",
      "unit": ["M","G","Mi","Gi"],
      "defaultUnit": "G",
      "required": "true",
      "display": "true"
    },
    {
      "description": "端口信息",
      "displayName": "端口信息",
      "name": "PORT",
      "value": "",
      "select": "",
      "type": "Ports",
      "required": "false"
    }
  ]}