apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    labels: 
      svc: ${NAME} 
      app: ${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    labels: 
      svc: ${NAME}
      app: store
    <% } %>

  spec:
    <% if(NODE_TYPE != null){ %>
    type: NodePort
    <% } %>
    ports:
    <% if(ports != null){ %> 
      <% for(port in ports){ %>
      - port: ${port.port}
        nodePort: ${port.nodePort}
        targetPort: ${port.targetPort}
        protocol: ${port.protocol}
        name: http-${port.targetPort}
      <% } %>
      <% } %>
      <% if(nodePorts != null){ %>   
      <% for(port in nodePorts){ %>
      - port: ${port.port}
        targetPort: ${port.targetPort}
        protocol: ${port.protocol}
        name: http-${port.targetPort}
      <% } %>
      <% } %>
    <% for(var i = 0; i < containerPorts.~size; i++){ %>
      - port: ${containerPorts[i].key}
        targetPort: ${containerPorts[i].key}
        protocol: ${containerPorts[i].value}
        name: http-${i}
     <% } %>
    selector:
      svc: ${NAME}
      <% if(APPLICATION_NAME !=  null) { %>
      app: ${APPLICATION_NAME}
      <% } %>

- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: ${NAME}
    <% if(APPLICATION_NAME != null) { %>
    namespace: application-${APPLICATION_NAME}
    labels: 
      svc: ${NAME}
      app: ${APPLICATION_NAME}
    <% } else { %>
    namespace: application-store
    labels: 
      svc: ${NAME}
      app: store
    <% } %>
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          svc: ${NAME}
          <% if(APPLICATION_NAME !=  null) { %>
          app: ${APPLICATION_NAME}
          <% } %>
      spec:
        containers:
          - name: ${NAME}
            image: 139.219.239.226/library/tomcat:8.5.15
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
            - name: PATH
              value: /usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: LANG
              value: C.UTF-8
            - name: JAVA_HOME
              value: /docker-java-home/jre
            - name: JAVA_VERSION
              value: 8u131
            - name: JAVA_DEBIAN_VERSION
              value: 8u131-b11-1~bpo8+1
            - name: CA_CERTIFICATES_JAVA_VERSION
              value: 20161107~bpo8+1
            - name: CATALINA_HOME
              value: /usr/local/tomcat
            - name: TOMCAT_NATIVE_LIBDIR
              value: /usr/local/tomcat/native-jni-lib
            - name: LD_LIBRARY_PATH
              value: /usr/local/tomcat/native-jni-lib
            - name: OPENSSL_VERSION
              value: 1.1.0f-3
            - name: GPG_KEYS
              value: 05AB33110949707C93A279E3D3EFE6B686867BA6 07E48665A34DCAFAE522E5E6266191C37C037D42 47309207D818FFD8DCD3F83F1931D684307A10A5 541FBE7D8F78B25E055DDEE13C370389288584E7 61B832AC2F1C5A90F0F9B00A1C506407564C17A3 713DA88BE50911535FE716F5208B0AB1D63011C7 79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED 9BA44C2621385CB966EBA586F72C284D731FABEE A27677289986DB50844682F8ACB77FC2E86E29AC A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23
            - name: TOMCAT_MAJOR
              value: 8
            - name: TOMCAT_VERSION
              value: 8.5.15
            - name: TOMCAT_TGZ_URL
              value: https://www.apache.org/dyn/closer.cgi?action
            - name: TOMCAT_ASC_URL
              value: https://www.apache.org/dist/tomcat/tomcat-8/v8.5.15/bin/apache-tomcat-8.5.15.tar.gz.asc
            resources:
              limits:
                <% if (LIMITS_CPU != null) { %>
                cpu: ${LIMITS_CPU}
                <% } %>
                <% if (LIMITS_MEMORY != null) { %>
                memory: ${LIMITS_MEMORY}
                <% } %>
              requests:
                <% if (REQUESTS_CPU != null) { %>
                cpu: ${REQUESTS_CPU}
                <% } %>
                <% if (REQUESTS_MEMORY != null) { %>
                memory: ${REQUESTS_MEMORY}
                <% } %>
            args:
              - catalina.sh
              - run
            imagePullPolicy: IfNotPresent

{"parameters":
  [
    {
      "description": "组件名称",
      "displayName": "名称",
      "name": "NAME",
      "value": "",
      "select": "",
      "type": "String",
      "required": "true"
    },
    {
      "description": "资源配置",
      "displayName": "修改资源会重新启动所有该组件下的实例",
      "name": "RESOURCE",
      "value": "",
      "select": "",
      "type": "Resource",
      "required": "false"
    },
    {
      "description": "端口信息",
      "displayName": "端口信息",
      "name": "PORT",
      "value": "",
      "select": "",
      "type": "Ports",
      "required": "false"
    }
  ]}