/**
 * Created by Zhang Haijun on 2016/8/9.
 */
//数据接口
app.constant('CONFIG', {
	'/login': '/statics/api/access/login.json',
	'/sso': '/statics/api/access/login.json',
	//退出
	"/logout": "/statics/api/assets/datacenter/dataCenter-modify.json",
	// 用户修改密码
	"/user/change": "/statics/api/assets/datacenter/dataCenter-modify.json",   //密码修改
	"/user/check": "/statics/api/assets/datacenter/dataCenter-modify.json",    //密码校验
	"/user/checkUser": "/statics/api/access/login.json",

	'/stats/dashboard': '/statics/api/graph/dashboard.json',
	'/statistic/computer': '/statics/api/graph/dashboard.json',
	'/vhost/performance': '/statics/api/graph/performance.json',
	'/vm/performance': '/statics/api/graph/performance.json',
	'/platform/hosts': '/statics/api/config/vmList.json',
	'/platform/abstracts': '/statics/api/config/vmList.json',
	'/platform/alarms': '/statics/api/config/vmList.json',
	// 数据中心
	"/dc/list": "/statics/api/assets/datacenter/dataCenter-list.json",
	"/dc/create": "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/modify": "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/remove": "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/load": "/statics/api/assets/datacenter/dataCenter-load.json",
	"/dc/basic": "/statics/api/assets/datacenter/dataCenter-basic.json",
	"/dc/detail": "/statics/api/assets/datacenter/dataCenter-detail.json",//基本信息

	"/dc/alarms": "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表
	"/dc/topLoad": "/statics/api/assets/datacenter/warnningServerList.json", //高负载服务器列表

	'/dc/freeClusters': '/statics/api/assets/datacenter/freeClusters.json',

	"/dc/graph": "/statics/api/assets/datacenter/graph.json",                 //3d图
	// 机房
	"/room/list": "/statics/api/assets/room/roomList.json",
	"/room/load": "/statics/api/assets/datacenter/dataCenter-load.json",
	"/room/create": "/statics/api/assets/room/roomList.json",
	"/room/modify": "/statics/api/assets/room/roomList.json",
	"/room/remove": "/statics/api/assets/room/roomList.json",
	"/room/detail": "/statics/api/assets/room/roomDetail.json",
	"/room/basic": "/statics/api/assets/room/roomDetail.json",
	"/room/alarms": "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表
	"/room/topLoad": "/statics/api/assets/datacenter/warnningServerList.json", //高负载服务器列表

	"/room/graph": "/statics/api/assets/room/graph.json",                       //3d图

	//机柜
	"/rack/list": "/statics/api/assets/rack/cabinetList.json",
	"/rack/create": "/statics/api/assets/rack/cabinetList.json",
	"/rack/modify": "/statics/api/assets/rack/cabinetList.json",
	"/rack/remove": "/statics/api/assets/rack/cabinetList.json",
	"/rack/detail": "/statics/api/assets/rack/cabinetDetail.json",
	"/rack/basic": "/statics/api/assets/rack/cabinetDetail.json",
	'/rack/load': '/statics/api/assets/datacenter/dataCenter-load.json',
	"/rack/alarms": "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表

	"/rack/graph": "/statics/api/assets/rack/graph.json",                       //3d图
	"/rack/freeServers": '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/dc/freeManagers": '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/room/freeServers": '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/paas/host/freeManagers": '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/paas/host/freeNodes": '/statics/api/assets/server/serviceList.json',   //游离服务器

	//服务器
	'/server/list': '/statics/api/assets/server/serverList.json',
	'/rack/resources': '/statics/api/assets/server/racksList.json',
	'/server/modify': '/statics/api/assets/server/serverList.json',
	'/server/create': '/statics/api/assets/server/serverList.json',
	'/server/remove': '/statics/api/assets/server/serverList.json',
	'/server/detail': '/statics/api/assets/server/serverDetail.json',
	'/server/basic': '/statics/api/assets/server/serverDetail.json',
	'/server/start': '/statics/api/assets/server/serverList.json',
    '/service/hpa': '/statics/api/assets/server/hpalist.json',
	'/server/stop': '/statics/api/assets/server/serverList.json',
	'/device/network/list': '/statics/api/assets/server/serverList.json',
	'/device/network/modify': '/statics/api/assets/server/serverList.json',
	'/device/network/create': '/statics/api/assets/server/serverList.json',
	'/device/network/start': '/statics/api/assets/server/serverList.json',
	'/device/network/stop': '/statics/api/assets/server/serverList.json',
	'/device/network/remove': '/statics/api/assets/server/serverList.json',
	'/device/network/detail': '/statics/api/assets/server/serverDetail.json',
	'/device/network/basic': '/statics/api/assets/server/serverDetail.json',
	'/device/storage/list': '/statics/api/assets/server/serverList.json',
	'/device/storage/modify': '/statics/api/assets/server/serverList.json',
	'/device/storage/start': '/statics/api/assets/server/serverList.json',
	'/device/storage/stop': '/statics/api/assets/server/serverList.json',
	'/device/storage/create': '/statics/api/assets/server/serverList.json',
	'/device/storage/remove': '/statics/api/assets/server/serverList.json',
	'/device/storage/detail': '/statics/api/assets/server/serverDetail.json',
	'/device/safety/list': '/statics/api/assets/server/serverList.json',
	'/device/safety/modify': '/statics/api/assets/server/serverList.json',
	'/device/safety/create': '/statics/api/assets/server/serverList.json',
	'/device/safety/start': '/statics/api/assets/server/serverList.json',
	'/device/safety/stop': '/statics/api/assets/server/serverList.json',
	'/device/safety/remove': '/statics/api/assets/server/serverList.json',
	'/device/safety/detail': '/statics/api/assets/server/serverDetail.json',
	'/device/safety/basic': '/statics/api/assets/server/serverDetail.json',
	'/server/load': '/statics/api/assets/datacenter/dataCenter-load.json',
	//（批量操作）
	'/server/batchStart': '/statics/api/assets/server/serverList.json',
	'/server/batchStop': '/statics/api/assets/server/serverList.json',
	'/server/batchRemove': '/statics/api/assets/server/serverList.json',
	'/device/network/batchStart': '/statics/api/assets/server/serverList.json',
	'/device/network/batchStop': '/statics/api/assets/server/serverList.json',
	'/device/network/batchRemove': '/statics/api/assets/server/serverList.json',
	'/device/safety/batchStart': '/statics/api/assets/server/serverList.json',
	'/device/safety/batchStop': '/statics/api/assets/server/serverList.json',
	'/device/safety/batchRemove': '/statics/api/assets/server/serverList.json',
	'/device/storage/batchStart': '/statics/api/assets/server/serverList.json',
	'/device/storage/batchStop': '/statics/api/assets/server/serverList.json',
	'/device/storage/batchRemove': '/statics/api/assets/server/serverList.json',
	'/res/vendor/store': '/statics/api/userCenter/department/distribute.json',
	//新增 资源关系
	'/res/rule/relations': '/statics/api/assets/datacenter/computer-list.json',
	'/res/rule/category': '/statics/api/assets/datacenter/Resource.json',
	'/res/res': '/statics/api/assets/datacenter/computer-list.json',

	//数据库管理
	'/db/ins/list': '/statics/api/application/applicationList.json',
	'/db/ins/create': '/statics/api/application/applicationList.json',
	'/db/ins/configs': '/statics/api/assets/rack/cabinetDetail.json',
	'/db/ins/sync': '/statics/api/application/applicationList.json',
	'/db/ins/remove': '/statics/api/application/applicationList.json',
	'/db/ins/reboot': '/statics/api/application/applicationList.json',
	'/db/ins/detail': '/statics/api/config/vmDetail.json',
	'/pdb/list': '/statics/api/application/applicationList.json',
	'/pdb/create': '/statics/api/application/applicationList.json',
	'/pdb/modify': '/statics/api/application/applicationList.json',
	'/pdb/remove': '/statics/api/application/applicationList.json',
	'/pdb/reboot': '/statics/api/application/applicationList.json',
	'/pdb/start': '/statics/api/application/applicationList.json',
	'/pdb/stop': '/statics/api/application/applicationList.json',
	'/application/topology': '/statics/api/config/tuopu.json',

	"/pool/listRes": "/statics/api/assets/pool/pool-resource.json",     //资源列表
	"/pool/addRes": "/statics/api/assets/pool/pool-resource.json",        //加入资源
	"/pool/delRes": "/statics/api/assets/pool/pool-resource.json",       //移除资源

	//镜像管理
	'/image/list': '/statics/api/assets/image/imageList.json',
	'/image/modify': '/statics/api/assets/image/imageList.json',
	'/image/detail': '/statics/api/assets/image/image-detail.json',
	'/image/sync': '/statics/api/assets/datacenter/dataCenter-load.json',
	'/image/remove': '/statics/api/assets/datacenter/dataCenter-load.json',
	//块设备管理
	'/volume/list': '/statics/api/assets/volume/volume-list.json',
	'/volume/create': '/statics/api/assets/volume/volume-list.json',
	'/volume/modify': '/statics/api/assets/volume/volume-list.json',
	'/volume/remove': '/statics/api/assets/volume/volume-list.json',
	'/volume/sync': '/statics/api/assets/volume/volume-list.json',
	'/volume/detail': '/statics/api/assets/image/image-detail.json',
	//快照管理
	'/snapshot/list': '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/create': '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/remove': '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/sync': '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/revert': '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/detail': '/statics/api/assets/image/image-detail.json',
	//配置管理
	'/flavor/list': '/statics/api/assets/size/size-list.json',
	'/flavor/sync': '/statics/api/assets/size/size-list.json',
	'/flavor/create': '/statics/api/assets/size/size-list.json',
	'/flavor/remove': '/statics/api/assets/size/size-list.json',
	'/flavor/detail': '/statics/api/assets/image/image-detail.json',
	//网络管理
	'/network/list': '/statics/api/assets/network/network-list.json',
	'/network/create': '/statics/api/assets/network/network-list.json',
	'/network/remove': '/statics/api/assets/network/network-list.json',
	'/network/modify': '/statics/api/assets/network/network-list.json',
	'/network/addnode': '/statics/api/assets/network/nodelist.json',
	'/network/detail': '/statics/api/assets/image/image-detail.json',
	//子网管理
	'/subnet/list': '/statics/api/assets/network/network-list.json',
	'/subnet/create': '/statics/api/assets/network/network-list.json',
	'/subnet/remove': '/statics/api/assets/network/network-list.json',
	'/subnet/detail': '/statics/api/assets/subnet/subnet-detail.json',
	//端口
	'/port/list': '/statics/api/assets/network/network-list.json',
	'/port/create': '/statics/api/assets/network/network-list.json',
	'/port/remove': '/statics/api/assets/network/network-list.json',
	//安全组管理
	'/security/group/list': '/statics/api/assets/network/network-list.json',
	'/security/group/create': '/statics/api/assets/network/network-list.json',
	'/security/group/remove': '/statics/api/assets/network/network-list.json',
	'/security/group/sync': '/statics/api/assets/network/network-list.json',
	'/security/group/detail': '/statics/api/assets/image/image-detail.json',
	//路由
	'/route/list': '/statics/api/assets/network/network-list.json',
	'/route/create':'/statics/api/assets/datacenter/dataCenter-modify.json',
	'/route/modify':'/statics/api/assets/datacenter/dataCenter-modify.json',
	'/route/remove':'/statics/api/assets/datacenter/dataCenter-modify.json',
	'/route/detail': '/statics/api/userCenter/user/userDetail.json',
	//用户管理
	'/user/list': '/statics/api/userCenter/user/userList.json',
	'/user/modify': '/statics/api/userCenter/user/userList.json',
	'/user/create': '/statics/api/userCenter/user/userList.json',
	'/user/remove': '/statics/api/userCenter/user/userList.json',
	'/user/detail': '/statics/api/userCenter/user/userDetail.json',
	'/user/checkUsername': '/statics/api/assets/datacenter/dataCenter-modify.json',

	'/user/lock': '/statics/api/userCenter/user/userList.json',
	'/user/active': '/statics/api/userCenter/user/userList.json',
	'/user/reset': '/statics/api/userCenter/user/userList.json',
	'/user/auth': '/statics/api/userCenter/role/roleList.json',
	'/user/roles': '/statics/api/userCenter/role/roleList.json',
	'/user/accredit': "/statics/api/assets/datacenter/dataCenter-load.json",
	'/user/quota': '/statics/api/userCenter/role/roleList.json',
	'/user/res': '/statics/api/userCenter/department/distribute.json',
	'/user/assign': '/statics/api/userCenter/department/distribute.json',
	'/user/deleteRes': '/statics/api/userCenter/department/distribute.json',
	'/user/leadIn': "/statics/api/assets/datacenter/dataCenter-load.json",
	//角色管理
	'/role/list': '/statics/api/userCenter/role/roleList.json',
	'/role/modify': '/statics/api/userCenter/role/roleList.json',
	'/role/create': '/statics/api/userCenter/role/roleList.json',
	'/role/remove': '/statics/api/userCenter/role/roleList.json',
	'/role/detail': '/statics/api/userCenter/role/roleDetail.json',
	'/role/auth': '/statics/api/userCenter/permission/permissionList.json',
	'/role/auths': '/statics/api/userCenter/permission/permissionList.json',
	'/role/accredit': '/statics/api/assets/datacenter/dataCenter-load.json',
	'/role/commands': '/statics/api/userCenter/permission/permissionList.json',
	'/role/accCommand': '/statics/api/assets/datacenter/dataCenter-load.json',
	//权限管理
	'/auth/list': '/statics/api/userCenter/permission/permissionList.json',
	'/auth/remove': '/statics/api/userCenter/permission/permissionList.json',
	'/auth/create': '/statics/api/userCenter/permission/permissionList.json',
	'/auth/modify': '/statics/api/userCenter/permission/permissionList.json',
	'/auth/detail': '/statics/api/userCenter/permission/permissionDetail.json',
	'/auth/listParents': '/statics/api/userCenter/permission/permissionList.json',
	'/auth/list/icon': '/statics/api/userCenter/permission/permissionList.json',
	//组织机构
	'/department/list': '/statics/api/userCenter/department/departmentList.json',
	'/department/remove': '/statics/api/userCenter/department/departmentList.json',
	'/department/create': '/statics/api/userCenter/department/departmentList.json',
	'/department/modify': '/statics/api/userCenter/department/departmentList.json',
	'/department/detail': '/statics/api/userCenter/department/departmentDetail.json',
	'/department/quota': '/statics/api/userCenter/role/roleList.json',
	'/department/res': '/statics/api/userCenter/department/distribute.json',
	'/department/assign': '/statics/api/userCenter/department/distribute.json',
	'/res/list': '/statics/api/userCenter/department/distribute.json',
	'/department/deleteRes': '/statics/api/userCenter/department/distribute.json',
	//分组管理
	'/user/group/list': '/statics/api/userCenter/user/userList.json',
	'/user/group/remove': '/statics/api/userCenter/user/userList.json',
	'/user/group/create': '/statics/api/userCenter/user/userList.json',
	'/user/group/modify': '/statics/api/userCenter/user/userList.json',
	'/user/group/detail': '/statics/api/userCenter/group/groupDetail.json',
	'/user/group/users': '/statics/api/userCenter/user/userList.json',
	'/user/group/addUser': '/statics/api/userCenter/user/userList.json',
	'/user/group/resGroups': '/statics/api/userCenter/user/userList.json',
	'/user/group/addResGroup': '/statics/api/userCenter/user/userList.json',
	'/user/group/listUser': '/statics/api/userCenter/group/group.json',
	'/user/group/listResGroup': '/statics/api/userCenter/group/group.json',

	'/res/group/list': '/statics/api/userCenter/user/userList.json',
	'/res/group/remove': '/statics/api/userCenter/user/userList.json',
	'/res/group/create': '/statics/api/userCenter/user/userList.json',
	'/res/group/modify': '/statics/api/userCenter/user/userList.json',
	'/res/group/detail': '/statics/api/userCenter/group/groupDetail.json',
	'/res/group/addRes': '/statics/api/userCenter/user/userList.json',
	'/res/group/listRes': '/statics/api/userCenter/group/group.json',
	'/res/group/deleteRes': '/statics/api/userCenter/user/userList.json',
	//云供应商管理
	"/cloudVendor/list": '/statics/api/config/supplier.json',
	'/cloudVendor/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/detail': '/statics/api/config/vmDetail.json',
	'/cloudVendor/checkName': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/lock': '/statics/api/config/supplier.json',
	'/cloudVendor/active': '/statics/api/config/supplier.json',
	'/cloudVendor/sync': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/listAccounts': '/statics/api/config/identity.json',
	'/region/list': '/statics/api/userCenter/group/group.json',
	//环境管理
	'/environment/list': '/statics/api/assets/image/imageList.json',
	'/environment/modify': '/statics/api/assets/image/imageList.json',
	'/environment/create': '/statics/api/assets/datacenter/dataCenter-load.json',
	'/environment/remove': '/statics/api/assets/datacenter/dataCenter-load.json',
	'/environment/detail': '/statics/api/config//environmentDetail.json',
	'/environment/createKubernetesCluser': '/statics/api/config//createKubernetesCluser.json',

	//平台管理
	'/environment/getNameSpace':'/statics/api/config//getNameSpace.json',

	"/openshift/cluster/list": '/statics/api/config/supplier.json',
	'/openshift/cluster/create': '/statics/api/assets/datacenter/dataCenter-modify.json',

	'/cluster/detail': '/statics/api/config/vmDetail.json',
	'/cluster/create': '/statics/api/config/vmDetail.json',
	'/cluster/remove': '/statics/api/config/vmDetail.json',
	'/cluster/addHost': '/statics/api/config/vmDetail.json',
	'/cluster/removeHost': '/statics/api/config/vmDetail.json',
	'/datastore/detail': '/statics/api/config/vmDetail.json',
	'/environment/receiveCluster': '/statics/api/config/receiveCluster.json',
	'/host/queryNormalHost':'/statics/api/config/aviableMaster.json',
	'/host/queryHostInEnv':'/statics/api/config/aviableMaster.json',

	//云主机管理
	"/service/host": '/statics/api/config/vmList.json',
    "/host/list": '/statics/api/config/vmList.json',
	"/vm/networks": '/statics/api/config/vmNetwork.json',
	"/vm/migrate": '/statics/api/config/vmList.json',
	'/vm/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/detail': '/statics/api/config/vmDetail.json',
	'/vm/pause': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/suspend': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/active': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/restart': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/backup': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/recovery': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/start': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/stop': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/sync': '/statics/api/assets/volume/volume-list.json',
	'/vm/clone': '/statics/api/assets/volume/volume-list.json',
	'/vm/OSMigrate': '/statics/api/assets/volume/volume-list.json',
	'/vm/snapshot': '/statics/api/assets/volume/volume-list.json',
	'/vm/batchRemove': '/statics/api/assets/volume/volume-list.json',
	'/vm/batchReboot': '/statics/api/assets/volume/volume-list.json',
	'/vm/batchStart': '/statics/api/assets/volume/volume-list.json',
	'/vm/batchStop': '/statics/api/assets/volume/volume-list.json',
	'/vm/vncconsole':'/statics/api/assets/datacenter/dataCenter-modify.json',
	'/datastore/servers': '/statics/api/personal/applyList.json',
	'/datastore/hosts': '/statics/api/personal/applyList.json',
	'/network/servers': '/statics/api/personal/applyList.json',
	'/host/create': '/statics/api/config/hostCreate.json',
	// '/host/checkName': '/statics/api/config/checkVmNameUnique.json',
	// '/host/checkIp': '/statics/api/config/checkIpUnique.json',
	'/host/remove': '/statics/api/config/hostRemove.json',
	'/host/modify': '/statics/api/config/hostModify.json',
	'/host/detail': '/statics/api/config/editVmDetail.json',
	'/environment/deleteNode': '/statics/api/config/removeHost.json',
	'/environment/addNode':'/statics/api/config/addHost.json',
	'/environment/queryNormalEnv':'/statics/api/config/aviableMaster.json',
	'/host/scheduleNode':'/statics/api/config/changeStatus.json',

	'/res/event/list': '/statics/api/assets/volume/volume-list.json',
	'/image/listName': '/statics/api/assets/volume/volume-list.json',
	'/list/listVersion': '/statics/api/assets/volume/volume-list.json',
	'/flavor/listFlavor': '/statics/api/userCenter/group/group.json',

	'/vdc/list': '/statics/api/config/vmList.json',
	'/cloudVendor/sync': '/statics/api/config/vmList.json',
	'/cluster/list': '/statics/api/config/vmList.json',
	'/cluster/sync': '/statics/api/config/vmList.json',
	'/vhost/list': '/statics/api/config/vmList.json',
	'/vhost/create': '/statics/api/config/vmList.json',
	'/vhost/remove': '/statics/api/config/vmList.json',
	'/vhost/move': '/statics/api/config/vmList.json',
	'/vhost/disconnect': '/statics/api/config/vmList.json',
	'/vhost/exitmaintain': '/statics/api/config/vmList.json',
	'/vhost/reconnect': '/statics/api/config/vmList.json',
	'/vhost/entermaintain': '/statics/api/config/vmList.json',
	'/vhost/sync': '/statics/api/config/vmList.json',
	'/vhost/detail': '/statics/api/config/vmDetail.json',
	'/datastore/list': '/statics/api/config/vmList.json',
	'/datastore/sync': '/statics/api/config/vmList.json',
	'/vdc/hosts': '/statics/api/config/networkCard.json',
	'/network/createDSwitch': '/statics/api/config/vmList.json',
	'/vhost/createVSwitch': '/statics/api/config/vmList.json',
	'/vhost/listvmbyvhost': '/statics/api/userCenter/department/distribute.json',
	//监控
	'/monitor/query': '/statics/api/monitor/query/cpu.json',
	//告警管理
	'/alarm/list': '/statics/api/config/vmList.json',
	'/alarm/detail': '/statics/api/config/vmDetail.json',
	//日志
	'/log/list': '/statics/api/log/list.json',
//软件仓库
	"/registry/count": '/statics/api/openstack/opstack.json',
	"/registry/images": '/statics/api/config/supplier.json',
	"/registry/create": "/statics/api/assets/room/roomList.json",
	"/registry/modify": "/statics/api/assets/room/roomList.json",
	"/registry/remove": "/statics/api/assets/room/roomList.json",
	'/registry/detail': '/statics/api/config/vmDetail.json',
    "/registry/list": '/statics/api/config/supplier.json',

	//////////////////镜像
	"/image/list": '/statics/api/config/supplier.json',
	"/image/modify": '/statics/api/openstack/opstack.json',
	"/image/create": "/statics/api/assets/room/roomList.json",//导入
	"/image/remove": "/statics/api/assets/room/roomList.json",
	'/image/detail': '/statics/api/config/vmDetail.json', //详情
	'/image/deployImage': '/statics/api/config/vmDetail.json', //详情
    '/api/build': '/statics/api/config/vmDetail.json', //详情

	'/application/monitor': '/statics/api/openstack/apply.json',
	'/host/monitor/gpu': '/statics/api/openstack/gpuApply.json',
	"/application/deleteResource": '/statics/api/openstack/opstack.json',
	"/app/log/list": '/statics/api/log/list.json',
	"/container/total": '/statics/api/openstack/opstack.json',
	"/container/list": '/statics/api/openstack/k8slist.json',
	"/container/node/list": '/statics/api/openstack/k8slist.json',
	"/container/event": '/statics/api/openstack/event.json',
	"/openshift/cluster/node": '/statics/api/openstack/event.json',
	"/openshift/cluster/create/node": '/statics/api/openstack/event.json',
	'/application/layout': '/statics/api/log/list.json',
		'/application/store/list': '/statics/api/application/moduleList.json',
'/openshift/cluster/detail': '/statics/api/config/vmDetail.json',
// '/application/monitor': '/statics/api/config/vmDetail.json',

	"/compose/create": "/statics/api/assets/room/roomList.json",
	"/compose/modify": "/statics/api/assets/room/roomList.json",
	"/compose/remove": "/statics/api/assets/room/roomList.json",

//定时任务
	"/layout/list": '/statics/api/config/supplier.json',
	"/task/taskDefs": '/statics/api/openstack/k8slist.json',
	"/task/task": "/statics/api/assets/room/roomList.json",
	"/task/check/name": "/statics/api/assets/room/roomList.json",
	'/task/taskDef': '/statics/api/config/vmDetail.json',

	"/task/search":'/statics/api/openstack/k8slist.json',
	"/task/template":'/statics/api/process/workflow.json',
	"/workflow/total": '/statics/api/openstack/k8slist.json',
	"/workflow/search/workflowDef":'/statics/api/openstack/k8slist.json',
	"/workflow/workflowDefs":'/statics/api/config/supplier.json',
	"/workflow/workflowDef":'/statics/api/process/layoutDetail.json',
	"/workflow/update/workflowDef": '/statics/api/openstack/opstack.json',
	"/workflow/check/name": '/statics/api/openstack/opstack.json',
	'/workflow/start': '/statics/api/config/vmDetail.json',
		'/workflow/execute': '/statics/api/config/vmDetail.json',
	"/task/param":'/statics/api/process/parame.json',
	 "/task/ouput/param":'/statics/api/process/parameout.json',
	"/workflow/task":'/statics/api/process/workflow.json',
	"/workflow/workflow":'/statics/api/process/workflowDetail.json',
		"/workflow/workflowDefJSON":'/statics/api/process/layoutDetail.json',

	"/layout/create": "/statics/api/assets/room/roomList.json",
	"/layout/modify": "/statics/api/assets/room/roomList.json",
	"/layout/remove": "/statics/api/assets/room/roomList.json",
	'/layout/detail': '/statics/api/config/vmDetail.json',
	'/layout/modellist': "/statics/api/assets/pool/modellist.json",

	"/compose/list": '/statics/api/config/supplier.json',
	"/compose/create": "/statics/api/assets/room/roomList.json",
	"/compose/modify": "/statics/api/assets/room/roomList.json",
	"/compose/remove": "/statics/api/assets/room/roomList.json",
	'/compose/detail': '/statics/api/config/vmDetail.json',

"/openshift/cluster/listOpenshiftClusterByAppId": "/statics/api/assets/room/roomList.json",
"/image/authorize": "/statics/api/assets/room/roomList.json",
'/deployHistory/list': '/statics/api/application/historyList.json',
"/application/editRcResource": "/statics/api/assets/room/roomList.json",
	'/diagram/data': '/statics/api/openstack/memory.json',
	"/application/autoScale": '/statics/api/config/supplier.json',
	"/application/list": '/statics/api/config/supplier.json',
	"/application/create": "/statics/api/assets/room/roomList.json",
	"/application/modify": "/statics/api/assets/room/roomList.json",
	"/application/remove": "/statics/api/assets/room/roomList.json",
	'/application/detail': '/statics/api/config/vmDetail.json',
	"/application/rolling": '/statics/api/config/supplier.json',
	"/application/layoutDeploy": '/statics/api/assets/room/roomList.json',
	"/application/ingress": '/statics/api/assets/room/ingress.json',
    "/application/service/port": '/statics/api/assets/room/port.json',
	"/application/store/tempalate":'/statics/api/application/tempalate.json',
	"/application/store/deploy/type":'/statics/api/config/supplier.json',
	'/application/resource':'/statics/api/config/supplier.json',


//k8s
	'/container/detail': '/statics/api/openstack/detail.json',
	"/statisticApp/listResource": '/statics/api/config/supplier.json',
	"/compose/create": "/statics/api/assets/room/roomList.json",
	"/compose/modify": "/statics/api/assets/room/roomList.json",
	"/compose/remove": "/statics/api/assets/room/roomList.json",
	'/statisticApp/total': '/statics/api/openstack/opstack.json',
	//个人中心
	'/message/list': '/statics/api/personal/messageList.json',
	'/applyRecord/list': '/statics/api/config/vmList.json',
	'/message/remove': '/statics/api/alarm/alarmList.json',
	'/message/detail': '/statics/api/personal/infoDetail.json',
	'/applyRecord/create': '/statics/api/personal/messageList.json',
	'/applyRecord/apply': '/statics/api/personal/messageList.json',
	'/apply/mine': '/statics/api/operation/taskList.json',
	'/applyRecord/detail': '/statics/api/personal/applyDetail.json',
	'/applyRecord/approveDetail': '/statics/api/personal/applyDetail.json',
	'/applyRecord/deal': '/statics/api/personal/applyList.json',
	'/applyRecord/done': '/statics/api/operation/taskList.json',
	'/applyRecord/approve': '/statics/api/operation/taskList.json',
	'/applyRecord/refuse': '/statics/api/operation/taskList.json',
	'/applyRecord/applyUser': '/statics/api/userCenter/user/applyList.json',
	//系统参数
	"/dict/statistic": '/statics/api/system/canshu.json',
	"/dict/batchModify": '/statics/api/system/modifyParams.json',
	"/jenkinsCredential/queryCredentialId": '/statics/api/system/canshu.json',
	//系统字典
	'/dict/list': '/statics/api/config/dictionaryList.json',
	// '/dict/list': '/statics/api/config/dictList.json',
	'/dict/children': '/statics/api/config/dictionaryList.json',
	'/dict/template': '/statics/api/config/dictTemplate.json',
	'/dict/create': '/statics/api/config/dictCreate.json',
	//负载管理
    "/loadBalance/list": '/statics/api/assets/datastore/loadBalanceList.json',
    "/loadBalance/create": '/statics/api/assets/datastore/loadBalanceCreate.json',
    "/loadBalance/modify": '/statics/api/assets/datastore/loadBalanceModify.json',
    "/loadBalance/detail": '/statics/api/assets/datastore/loadBalanceDetail.json',
    "/loadBalance/remove": '/statics/api/assets/datastore/loadBalanceRemove.json',
    "application/listByLayout": '/statics/api/assets/datastore/applicationList.json',
    //存储卷
	"/pv/list": '/statics/api/assets/store/pvList.json',
	// "/pv/queryPVTemplate": '/statics/api/assets/store/queryPVTemplate.json',
	// "/pv/queryPVTemplate": '/statics/api/assets/store/queryPVTemplate1.json',
	"/pv/queryPVTemplate": '/statics/api/assets/store/queryPVTemplate2.json',
	"/pv/create": '/statics/api/assets/store/pvCreate.json',
	"/pv/remove": '/statics/api/assets/store/pvRemove.json',
	"/pv/detail": '/statics/api/assets/store/pvDetail.json',
	"/pv/modify": '/statics/api/assets/store/pvModify.json',
	//应用实例
	'/service/list':'/statics/api/application/instance/serviceList.json',
	'/service/list/job':'/statics/api/assets/room/roomList.json',
	'/service/job':'/statics/api/assets/room/roomList.json',
	'/service/remove':'/statics/api/application/instance/serviceRemove.json',
	'/service/rolling':'/statics/api/application/instance/serviceRolling.json',
	'/service/scale':'/statics/api/application/instance/serviceScale.json',
	'/service/deploy':'/statics/api/application/instance/serviceDeploy.json',
	'/service/detail':'/statics/api/application/instance/serviceDetail.json',
		'/image/inspectImage':'/statics/api/application/instance/getimagemessage.json',
		'/service/deploy':'/statics/api/application/instance/serviceList.json',
		'/service/alarm':'/statics/api/application/instance/serviceAlarm.json',
	'/service/update/alarm':'/statics/api/application/instance/updateAlarm.json',
	//服务组件
    '/application/store/content':'/statics/api/application/store/storeContent.json',
	'/application/store/deploy':'/statics/api/application/store/storeDeploy.json',
	'application/store/service':'/statics/api/application/store/temp.json',
    // 数据纵览
	'/statistic/statistic':'/statics/api/dashboard/statisticDashboard.json',
	'/statistic/application':'/statics/api/dashboard/statisticApplication.json',
	// 系统运维
	'/eslog/list':'/statics/api/system/eslogList.json',
	'/environment/getMonitorUrl':'/statics/api/system/getMonitorUrl.json',
	'/eslog/sysLogList':'/statics/api/system/sysLogList.json',
	'/eslog/sysLogDetail':'/statics/api/system/sysLogDetail.json',

	//应用编排迁移接口
	"/layout/template/list": '/statics/api/application/template/templatelist.json',
	"/layout/template/create": '/statics/api/application/template/createtemplate.json',
	"/layout/template/modify": '/statics/api/application/template/modifytemplate.json',
	"/layout/template/remove": '/statics/api/application/template/removetemplate.json',
	"/layout/template/version/list": '/statics/api/application/template/versionlist.json',
	"/layout/template/version/create": '/statics/api/application/template/addtempversion.json',
	"/layout/template/version/detail": '/statics/api/application/template/tempversiondetail.json',
	"/layout/template/version/upgrade": '/statics/api/application/template/tempversionupgrade.json',
	"/layout/template/version/modify": '/statics/api/application/template/tempversionmodify.json',
	"/layout/template/version/remove": '/statics/api/application/template/tempversionremove.json',
	"/layout/template/getList":'/statics/api/application/template/templatelist.json',
	//配置管理
    "/config/manage/config": '/statics/api/application/template/templatelist.json',
	
	// 代码仓库
	'/code/repository/code': '/statics/api/process/codeRepository/codeRepositoryList.json',
	
});
